pred show {}
run  show for 1

abstract sig c1_CYGNUM_HAL_QUICC_SCC2_ABSTRACT
{}
{}
abstract sig c2_CYGNUM_HAL_QUICC_SCC3_ABSTRACT
{}
{}
abstract sig c3_CYGINT_HAL_TESTS_NO_CACHES_ABSTRACT
{}
{ (#(c3_CYGINT_HAL_TESTS_NO_CACHES_ABSTRACT) = 0) => (no c4_CYGINT_HAL_TESTS_NO_CACHES) }
lone sig c4_CYGINT_HAL_TESTS_NO_CACHES
{ ref : lone Int }
{ all cl0 : this.@ref | cl0 = #(c3_CYGINT_HAL_TESTS_NO_CACHES_ABSTRACT)
  #(c3_CYGINT_HAL_TESTS_NO_CACHES_ABSTRACT) > 0 }
lone sig c5_CYGHWR_HAL_POWERPC_ADDER_II
{ r_c6_CYGNUM_HAL_QUICC_SCC2_ABSTRACT : one c6_CYGNUM_HAL_QUICC_SCC2_ABSTRACT
, r_c7_CYGNUM_HAL_QUICC_SCC3_ABSTRACT : one c7_CYGNUM_HAL_QUICC_SCC3_ABSTRACT }
{}
lone sig c6_CYGNUM_HAL_QUICC_SCC2_ABSTRACT extends c1_CYGNUM_HAL_QUICC_SCC2_ABSTRACT
{}
{ one r_c6_CYGNUM_HAL_QUICC_SCC2_ABSTRACT }
lone sig c7_CYGNUM_HAL_QUICC_SCC3_ABSTRACT extends c2_CYGNUM_HAL_QUICC_SCC3_ABSTRACT
{}
{ one r_c7_CYGNUM_HAL_QUICC_SCC3_ABSTRACT }
